name: NPM
on:
  schedule:
    - cron: '0 16 * * *'
jobs:
  npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: install ruby
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.7
      - name: Update NPM cache
        run: |
          git config --local user.name "GitHub"
          git config --local user.email "noreply@github.com"
          bin/npm
